/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-10-03

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "macros_utiles.h"
volatile char c = 'e';
volatile char c2 = 'e';
volatile int cmpt = 0;
volatile int NouvelleEcriture = 0;

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
void configLCD(){
		RCC->AHB1ENR |= BIT3 +BIT4; //activation des clk pour GPIO D et E
		GPIOE->MODER |= (BIT0 + BIT2+ BIT4); //Mise sur output des pins PE0,PE1,PE2
		GPIOD->MODER |= (BIT0|BIT2|BIT4|BIT6|BIT8|BIT10|BIT12|BIT14);//data D0 a D7 en mode sortie
}
//Shift the display and the cursor's position to the right


void CursorRight(){
	GPIOD->ODR &= ~(0xff);//remise a 0
	GPIOE->ODR &= ~(0xff);//remise a 0
	GPIOD->ODR |= BIT2+BIT3+BIT4; //commande de shift de curseur a droite
	for (int k = 0; k < 100000; k++){}
	GPIOE->ODR |= BIT2;// enable 1 logique
	for (int k = 0; k < 100000; k++){}
	GPIOE->ODR &= ~(0xff);// enable 0 logique et remise a 0
}


void CursorLeft(){
	GPIOD->ODR &= ~(0xff);//remise a 0
	GPIOE->ODR &= ~(0xff);
	GPIOD->ODR |= BIT4;
	for (int k = 0; k < 10000; k++){}
	GPIOE->ODR |= BIT2;// enable 1 logique
	for (int k = 0; k < 10000; k++){}
	GPIOE->ODR &= ~(0xff);// enable 0 logique et remise a 0
}

void CursorStartLine(){// met le curseur au debut de la ligne
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
	CursorLeft();
}


void ClearLCD(){
	GPIOD->ODR &= ~(0xff);//remise a 0
	GPIOE->ODR &= ~(0xff);
	GPIOD->ODR |= BIT0;
	for (int k = 0; k < 100000; k++){}
	GPIOE->ODR |= BIT2;// enable 1 logique
	for (int k = 0; k < 100000; k++){}
	GPIOE->ODR &= ~(0xff);// enable 0 logique et remise a 0
}
void writeByteLCD(__IO uint8_t d){
	GPIOD->ODR &= ~(0xff);//remise a 0
	GPIOD->ODR |= d; // ecris l'octet
	GPIOE->ODR |= BIT0;// bit pour signifier qu'on ecrit
	for (int k = 0; k < 100000; k++){}
	GPIOE->ODR |= BIT2; // enable 1 logique
	for (int k = 0; k < 100000; k++){}
	GPIOE->ODR &= ~(0xff);// enable 0 logique et remise a 0
}

void writeStringLCD(const char * p_str){
	int i =0;
	while(p_str[i] != '\0'){ // tant que transmission pas complete
		writeByteLCD(p_str[i++]);
		}
}

void CursorHome(){
	GPIOD->ODR &= ~(0xff);//remise a 0
	GPIOD->ODR |= (BIT1);// cursor return home
	for (int k = 0; k < 100000; k++){}
	GPIOE->ODR |= BIT2;// enable 1 logique
	for (int k = 0; k < 100000; k++){}
	GPIOE->ODR &= ~(0xff);// enable 0 logique et remise a 0
}

void WriteControl(){// instructions pour initialiser le lcd
	GPIOE->ODR &= ~(0xff);//RS=0;R/W=0;E=0
	GPIOD->ODR &= ~(0xff);
	GPIOD->ODR |= (BIT3+BIT4+BIT5);//set on 8 bits 2 lines
	for (int k = 0; k < 100000; k++){}//4s
	GPIOE->ODR |= BIT2;// enable 1 logique
	for (int k = 0; k < 100000; k++){}
	GPIOE->ODR &= ~(0xff);// enable 0 logique et remise a 0


	GPIOD->ODR &= ~(0xff);//remise a 0
	GPIOD->ODR |= (BIT1+BIT2+BIT3);//LCD on/off control
	for (int k = 0; k < 100000; k++){}
	GPIOE->ODR |= BIT2;
	for (int k = 0; k < 100000; k++){}
	GPIOE->ODR &= ~(0xff);


}


void Gpio_key_Init(){
	GPIOD->MODER |= BIT24; //Mise

}

void configureAndStartSystick(int p_freq){//hologe du processeur est 53.73Mhz, l'autre est 53.73Mhz/8
	const int systick_clk = 53760000/8;// on doit utiliser l'horloge du processeur pour pouvoir utiliser des insterruptions(trop rapide)
	SysTick->LOAD = systick_clk/p_freq;//on compte jusqu'a 1
	SysTick->CTRL |= BIT0 |BIT1;//BIT0 pour Enable et BIT1 pour Enable SysTick exception request
	SysTick->VAL = systick_clk/p_freq;//lire ou ecrire en tout temps la valeur du compteur
}
/*
int main(void)
{
	volatile int compteurRetourDebutLaLigne = 0;//garde en memoire la position du curseur
	Gpio_key_Init();// init GPIO pour le keypad
	configureAndStartSystick(8);//frequence a laquelle on lit le clavier (10Hz)
	configLCD();// GPIO pour le lcd
	WriteControl();// instructions pour initialiser le lcd
	ClearLCD();
	CursorHome();
	writeStringLCD("SMI_EE_WG                               ");
  while(1){
	  if(NouvelleEcriture == 1){// si on appui sur quelquechose
		  if(c=='#'){ // si on appui sur #
			  for(int k=0;k<compteurRetourDebutLaLigne;k++){CursorLeft();}//on met le curseur au debut de la ligne 2
			  writeStringLCD("                ");// on ecrit des espaces sur toute la ligne
			  compteurRetourDebutLaLigne = 16;// on indique qu'on est au bout de la ligne pour revenir au debut (voir le if ligne 214)
		  }else if (cmpt < 3){// si on appui sur 2 ou 1 touche
			  writeByteLCD(c);// on ecrit la valeur du premier bouton appuye
			  if(cmpt > 1 && c2 != 'e' && compteurRetourDebutLaLigne < 15){// si on appui sur 2 touches en meme temps
			  // la deuxieme condition est pour si la valeur de la deuxieme touche n a pas ete chargee dans c2
			  //La troisieme condition est pour savoir si on a la place d ecrire 2 caratere
				  writeByteLCD(c2);// on ecrit la valeur du deuxieme bouton appuye
				  compteurRetourDebutLaLigne +=1;
			  			  }
			  compteurRetourDebutLaLigne +=1;
		  }
		  cmpt = 0;
		  c2 = 'e';
		  for (int k = 0; k < 1000000; k++){}//anti rebonds
		  NouvelleEcriture = 0;
	  }
	  if(compteurRetourDebutLaLigne >= 16){// on est a la fin de la ligne
		  CursorStartLine();// on remet automatiquement le curseur au debut de la ligne
		  compteurRetourDebutLaLigne = 0;
	  }
  }
}*/

void nouvEcriture(char n) {
	if(cmpt == 0){// si on appui sur une touche
		c = n;
	} else if (n != c) {// si on appui sur deux touches (deuxieme fois qu'on utilise nouvEcriture pour une autre touche)
	c2 = n;
	}
	NouvelleEcriture = 1;
	cmpt++;
}

void SysTick_Handler(void) {
	cmpt = 0;// compte le nombre de touches appuyees
	for (int i = 0; i < 5; i++) {
	            // Activer la ligne i
	            GPIOA->ODR = ~(1 << i);

	            for (int k = 0; k < 1000; k++){}

	            	if(GPIOA->ODR== 0xfffe){// Lire la rang�e 1
	            		if ((GPIOC->IDR | (BIT5|BIT6)) == 0xffef) {// Lire la colonne 1 de la rang�e 1, "| (BIT5|BIT6)" pour forcer les bits qui nous interessent pas a 1
	            			nouvEcriture('1');
	            		}
	            		if ((GPIOC->IDR | (BIT4|BIT6))==0xffdf) {// Lire la colonne 2 de la rang�e 1
	            			nouvEcriture('2');
	            		}
	            		if ((GPIOC->IDR | (BIT4|BIT5))==0xffbf) {// Lire la colonne 3 de la rang�e 1
	            			nouvEcriture('3');
	            		}
	            	}
	            	if(GPIOA->ODR == 0xfffd){//Lire la rangee 2
	            		if ((GPIOC->IDR | (BIT5|BIT6))==0xffef) {
	            			nouvEcriture('4');
	            		}
	            		if ((GPIOC->IDR | (BIT4|BIT6))==0xffdf) {
	            			nouvEcriture('5');
	            		}
	            		if ((GPIOC->IDR | (BIT4|BIT5))==0xffbf) {
	            			nouvEcriture('6');
	            		}
	            	}
	            	if(GPIOA->ODR == 0xfffb){
	            		if ((GPIOC->IDR | (BIT5|BIT6)) ==0xffef) {
	            			nouvEcriture('7');
	            		}
	            		if ((GPIOC->IDR | (BIT4|BIT6)) ==0xffdf) {
	            			nouvEcriture('8');
	            		}
	            		if ((GPIOC->IDR | (BIT4|BIT5)) ==0xffbf) {
	            			nouvEcriture('9');
	            		}
	            	}
	            	if(GPIOA->ODR == 0xfff7){
	            		if ((GPIOC->IDR | (BIT5|BIT6)) ==0xffef) {
	            			nouvEcriture('*');
	            		}
	            		if ((GPIOC->IDR | (BIT4|BIT6))==0xffdf) {
	            			nouvEcriture('0');
	            		}
	            		if ((GPIOC->IDR | (BIT4|BIT5))==0xffbf) {

	            			c = '#';
	            			NouvelleEcriture = 1;
	            		}
	            	}
	            // D�sactiver la ligne i
	            GPIOA->ODR = (1 << i); // Met le bit i � 0
	}
}
