/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-10-03

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "macros_utiles.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
void InitUart(void){
	//p62, PA0 connecte a uart tx et PA1 a rx (colone AF8)
	RCC->AHB1ENR |= BIT0; //enable clk for gpioA

	GPIOA->MODER |= BIT1 | BIT3;
	GPIOA->AFR[0] |= BIT7 | BIT3;// fonction altenative 8 pour les 2 broches PA0 et PA1 (colone AF8)

	RCC->APB1ENR |= BIT19; //enable clk for UART

	UART4->CR1 |= BIT3 | BIT2;//BIT3 transmitter enable, BIT2 RECEPTION enable

	//NVIC->ISER[0] |= BIT28;

	//UART4->CR2 on touche pas aux autres Registres de controle
	//UART4->CR3

	//UART4->BRR = 7.29*16;//13.44Mhz feed au UART, on multiplie par 16 pour faire un bit shift pour prendre les 4 bits danas la partie frac et les mettres en entier
				  //voir page 978 refman 30.3.4, on cherche USARTDIV, on trouve USARTDIV =7.29, over8 est a 0 et clk a 13.44Mhz
	//pour un baud rate de 115200. brr = fclkUart"13.44Mhz"/(8*2*115200), on multiplie par 16 pour avoir une partie fractionnaire sur 4 bits

	UART4->BRR = 43.75*16;

	UART4->CR1 |= BIT13;//enable
}

void writeByte(char p_byte){
	while(!(UART4->SR & BIT7)){ // tant que transmission pas complete
	}
	UART4->DR = p_byte;
}

void writeUart(const char * p_str){
	volatile int i =0;
	while(p_str[i] != '\0'){ // tant que transmission pas complete
		writeByte(p_str[i++]);
		}
	writeByte('\0');
	//writeByte('\n');
}

char receiveByteUart(){
	while(!(UART4->SR & BIT5)){ // tant que transmission pas complete
		}
	return UART4->DR;
}


int main(void)
{
  //char reception;
  InitUart();


  /* TODO - Add your application code here */

  /* Infinite loop */
  while (1)
  {
	//writeUart("Hello World");
	char reception = receiveByteUart();

	writeByte(reception);
  }
}
