/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-10-25

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "macros_utiles.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
void GPIO_SPI_config(void){
	RCC->AHB1ENR |= BIT0;// enable clk GPIOA
	//AHB1 a un prescaler a 1 (53.73Mhz)
	GPIOA->MODER |= BIT9|BIT11|BIT13|BIT15;//alternate function sur les pinA 4,5,6,7 pour le spi
	GPIOA->MODER |= BIT0;// output de gpioa0 (PA0) pour l'utiliser comme chip select
	GPIOA->AFR[0] |= BIT16|BIT18|   BIT20|BIT22|   BIT24|BIT26|   BIT28|BIT30;//AF5(alternate fonction 5) pour les pin PA4,5,6 (AFR[0] car low register)

	GPIOA->ODR = BIT0;



	RCC->APB2ENR |= BIT12;//enable clk pour le SPI1,
	//APB2 a un prescaler a 2 qui est a la sortie du AHB1 a un prescaler (53.73/2Mhz)
	//peripheral_clk = 53760000/2

	SPI1->CR1 |=BIT5|BIT3|BIT2;
	//SPI1->CR1 |=BIT4;  //MSB first, 8 bit transmission, fullduplex,CPOL=0,CPHA=0, no crc
	//BIT 9 ssm=0, car pas de multi master
	//Bits 5:3, BR[2:0]: Baud rate control, ici fPCLK /8 donc (53.73/2)/8Mhz (le max de frequence est de 10Mhz max pour la eeprom(page3))
	//BIT11 Data frame format, frames de 8 bits, For an 8-bit data frame, the buffers are 8-bit and only the LSB of the register (SPI_DR[7:0]) is used for transmission/reception
	//BIT2 to be master
	SPI1->CR2 |=BIT2;// SSOE: SS output enable

}

uint16_t Read_byte_SPI(uint16_t adresse){

	volatile uint16_t _MISO = 0;
	volatile int debug = 10;

	SPI1->CR1 |=BIT6;//BIT 6, SPE: SPI enable
	GPIOA->ODR &= ~BIT0;
	//for(int i=0;i<10000;i++);
	SPI1->DR = 0x03;// instruction pour lire
	//debug = SPI1->DR;
	//while((SPI1->SR)&(BIT7));//tant que SPI busy
	while(((SPI1->SR)&(BIT1)) == 0);
	SPI1->DR = (uint8_t) (adresse & 0x00FF); //masquage des 8 MSB
	//debug = SPI1->DR;
	//while((SPI1->SR)&(BIT7));//tant que SPI busy
	while(((SPI1->SR)&(BIT1)) == 0);
	//SPI1->DR = (uint8_t) ((adresse>>8) & 0x00FF);// right shift de 8 pour mettre les 8 dernier bits d adresse
	SPI1->DR = 0x00;
	//while((SPI1->SR)&(BIT1));
	//SPI1->DR = 0x00;
	//while((SPI1->SR)&(BIT7));//tant que SPI busy
	while(((SPI1->SR)&(BIT0)) == 0);// tant que Rx buffer vide
	//debug = (SPI1->SR)&(BIT0);
	_MISO =  SPI1->DR;

	//debug = MISO;
	GPIOA->ODR = BIT0;

	SPI1->CR1 &=~BIT6;//SPI disable


	return _MISO;
}

void Write_byte_SPI(uint16_t adresse, uint8_t donnee){


	volatile int debug = 0;

	SPI1->CR1 |=BIT6;//BIT 6, SPE: SPI enable
	GPIOA->ODR &= ~BIT0;
	//for(int i=0;i<10000;i++);
	SPI1->DR = 0x06;// write enable (latch)
	//debug = SPI1->DR;
	while(!((SPI1->SR)&(BIT1)));// bit de transmission
	//debug = SPI1->DR;
	GPIOA->ODR = BIT0;
	//for(int i=0;i<10000;i++);
	//SPI1->CR1 &=~BIT6;//BIT 6, SPE: SPI enable
	//for(int i=0;i<10000;i++);
	//SPI1->CR1 |=BIT6;//BIT 6, SPE: SPI enable
	GPIOA->ODR &= ~BIT0;


	SPI1->DR = 0xff;// instruction pour écrire
	while(!((SPI1->SR)&(BIT1)));// bit de transmission

	SPI1->DR = (uint8_t) (adresse & 0x00FF); //masquage des 8 MSB
	while(!((SPI1->SR)&(BIT1)));// bit de transmission

	SPI1->DR = (uint8_t) ((adresse>>8) & 0x00FF);// right shift de 8 pour mettre les 8 dernier bits d adresse
	while(!((SPI1->SR)&(BIT1)));// bit de transmission
	SPI1->DR = 0x0a;
	//SPI1->DR = donnee;

	while(!((SPI1->SR)&(BIT1)));// bit de transmission

	GPIOA->ODR = BIT0;
	debug = GPIOA->ODR;

	SPI1->CR1 &=~BIT6;//SPI disable


}



int main(void)
{
  volatile uint16_t MISO = 10;
  GPIO_SPI_config();
  for(int i=0;i<10000;i++);
  Write_byte_SPI(0x0000,0x0A);
  for(int i=0;i<10000;i++);
  MISO = Read_byte_SPI(0x0000);
  while (1)
  {
  }
}
