/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2023-09-26

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "macros_utiles.h"

//#define DMA_ENABLE 1
#define array_size 1024


volatile int tableausource[array_size];
volatile int tableaudestination[array_size];
volatile int nbTransferts = 0;

#define DMA_ENABLE


void configureDMA(void){
	RCC->AHB1ENR |= BIT22;//clock enable DMA p250
	DMA2_Stream0->CR |=BIT14;//bit Msize a config en word p328
	DMA2_Stream0->CR |=BIT12;
	DMA2_Stream0->CR |=BIT10;//il faut incrementer l@ ou on ecrit a chaque transfert pour pas ecraser.
	DMA2_Stream0->CR |=BIT9;
	DMA2_Stream0->CR |=BIT8;//Quand le tableau est rempli, une interruption se fait et on reecrit au depart du tableau
	DMA2_Stream0->CR |=BIT7;//direction memoire a memoire
	DMA2_Stream0->CR |=BIT4;//creation interruption quand un transfert est fait

	DMA2_Stream0->NDTR =  array_size;//nombre de transferts a faire
	DMA2_Stream0->PAR = (int)tableausource;//adresse de depart
	DMA2_Stream0->M0AR = (int)tableaudestination;//destination

	NVIC->ISER[1]|= BIT24; //voir la position de la table
}
void startDMA(void){
	DMA2_Stream0->CR |=BIT0;//start le transfert
}
void configureAndStartSystick(void){//hologe du processeur est 53.73Mhz, l'autre est 53.73Mhz/8
	const int systick_clk = 53760000/8;// on doit utiliser l'horloge du processeur pour pouvoir utiliser des insterruptions(trop rapide)
	SysTick->LOAD = systick_clk/1;//on compte jusqu'a 1
	SysTick->CTRL |= BIT0 |BIT1|BIT2;
	SysTick->VAL = systick_clk/1;//lire ou ecrire en tout temps la valeur du compteur
}


/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
  volatile int i = 0;
  for(i = 0;i<array_size;i++){
	  tableausource[i] = i;
  }
  configureDMA();
  configureAndStartSystick();
#ifdef DMA_ENABLE
  startDMA();
#endif

  while (1)
  {
	i++;
#ifndef DMA_ENABLE
	for(i = 0;i<array_size;i++){
		  tableausource[i] = tableaudestination[i];
		  nbTransferts++;
	  }
#endif
  }
}

void DMA2_Stream0_IRQHandler(){
	DMA2->LIFCR|=BIT5;//p327 pour clear le flag pour le canal0
	nbTransferts++;
}
void SysTick_Handler(void){
	//pas besoin de config NVIC pour enable l'interruption
	nbTransferts = 0;
}
